import type { NotesData } from "@/types/notes";

export const MOCK_NOTES_DATA: NotesData = {
  userName: "Sam Wynne",
  dateRange: "Feb 19 — May 19, 2026",
  totalCheckInsCount: 74,
  metrics: [
    { label: "AVG ENERGY", value: "46%", subtext: "median 48%" },
    { label: "CRASHES", value: "11", subtext: "≥ 2-day PEM" },
    { label: "SLEEP", value: "6h 38m", subtext: "often broken" },
  ],
  triggers: [
    {
      id: "trig-1",
      title: "Social or extended conversation",
      subtitle: "6 of 6 events",
      impactText: "High impact",
    },
    {
      id: "trig-2",
      title: "Mental effort over 4 hours",
      subtitle: "Strong on screen-heavy days",
      impactText: "High impact",
    },
    {
      id: "trig-3",
      title: "Heat sensitivity",
      subtitle: "9 of 12 warm days",
      impactText: "High impact",
    },
  ],
  summaryParagraph:
    "Over 90 days, Sam's energy averaged 46%, with 11 confirmed PEM events typically delayed two or more days after triggering activity. Primary triggers are social interaction, sustained mental effort and heat sensitivity. Sleep averaged 6h 38m and was frequently broken. These patterns have been consistent across the full tracking period.",
  generatedDateText:
    "Generated by heedly on May 20, 2026 · self-reported + connected wearables · not a diagnostic instrument.",
};
