// import { MOCK_NOTES_DATA } from "@/data/mock";
//   ^ No longer read. Notes is a document someone may take to an appointment,
//     so sample values here were the most costly kind of placeholder. The mock
//     stays in the tree for the shapes it documents.
import { useFirstName } from "@/contexts/NameContext";
import type { NotesData } from "@/types/notes";

/**
 * Notes, showing only what can actually be derived today.
 *
 * That is the person's name and the date the page was produced. Averages,
 * crash counts, sleep and triggers all need analysis that does not exist, so
 * they come back empty. The UI keeps every row: a blank field says "not yet",
 * an invented one says something untrue on a page headed "for your
 * appointment".
 */

/** Labels are the screen's own wording; only the values are this person's. */
const EMPTY_METRICS: NotesData["metrics"] = [
  { label: "AVG ENERGY", value: "", subtext: "" },
  { label: "CRASHES", value: "", subtext: "" },
  { label: "SLEEP", value: "", subtext: "" },
];

const EMPTY_TRIGGERS: NotesData["triggers"] = [
  { id: "trig-1", title: "", subtitle: "", impactText: "" },
  { id: "trig-2", title: "", subtitle: "", impactText: "" },
  { id: "trig-3", title: "", subtitle: "", impactText: "" },
];

function generatedToday(): string {
  const today = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  return `Generated by heedly on ${today} · self-reported + connected wearables · not a diagnostic instrument.`;
}

export function useNotes() {
  // const [data] = useState<NotesData>(MOCK_NOTES_DATA);
  //   ^ Replaced by the real name and date plus empty values below.
  const { firstName } = useFirstName();

  const data: NotesData = {
    // Empty when they never gave one — a name is optional throughout.
    userName: firstName,
    dateRange: "",
    // Null, not 0: nothing counts check-ins yet, and 0 would be a claim.
    totalCheckInsCount: null,
    metrics: EMPTY_METRICS,
    triggers: EMPTY_TRIGGERS,
    summaryParagraph: "",
    generatedDateText: generatedToday(),
  };

  return {
    notes: data,
    userName: data.userName,
    dateRange: data.dateRange,
    totalCheckInsCount: data.totalCheckInsCount,
    metrics: data.metrics,
    triggers: data.triggers,
    summaryParagraph: data.summaryParagraph,
    generatedDateText: data.generatedDateText,
  };
}
