import { useRouter } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView, useSafeAreaInsets } from 'react-native-safe-area-context';

import { DawnBackground } from '@/components/core';
import { Spacing } from '@/constants/theme';

// ─── Design tokens ────────────────────────────────────────────────────────────

const COLORS = {
  background: '#F5DDD5',
  headingDark: '#2C1810',
  accent: '#C0634A',
  bodyText: '#785344',
  mutedText: '#715749ff',
  cardBg: 'rgba(255, 251, 248, 0.85)',
  cardBorder: 'rgba(212, 184, 174, 0.35)',
  metricBg: 'rgba(242, 216, 202, 0.55)',
  divider: 'rgba(212, 184, 174, 0.35)',
  buttonFill: '#D9735A',
  buttonText: '#FFFFFF',
  secondaryBtnBg: 'rgba(255, 251, 248, 0.95)',
  secondaryBtnBorder: 'rgba(212, 184, 174, 0.35)',
  panelBg: 'rgba(255, 245, 240, 0.95)',
  panelBorder: 'rgba(212, 184, 174, 0.4)',
};

// ─── Data structures for backend/API integration ────────────────────────────

type MetricSummary = {
  label: string;
  value: string;
  subtext: string;
};

type TriggerItem = {
  id: string;
  title: string;
  subtitle: string;
  impactText: string;
};

type NotesData = {
  userName: string;
  dateRange: string;
  totalCheckInsCount: number;
  metrics: MetricSummary[];
  triggers: TriggerItem[];
  summaryParagraph: string;
  generatedDateText: string;
};

const NOTES_DATA: NotesData = {
  userName: 'Sam Wynne',
  dateRange: 'Feb 19 — May 19, 2026',
  totalCheckInsCount: 74,
  metrics: [
    { label: 'AVG ENERGY', value: '46%', subtext: 'median 48%' },
    { label: 'CRASHES', value: '11', subtext: '≥ 2-day PEM' },
    { label: 'SLEEP', value: '6h 38m', subtext: 'often broken' },
  ],
  triggers: [
    {
      id: 'trig-1',
      title: 'Social or extended conversation',
      subtitle: '6 of 6 events',
      impactText: 'High impact',
    },
    {
      id: 'trig-2',
      title: 'Mental effort over 4 hours',
      subtitle: 'Strong on screen-heavy days',
      impactText: 'High impact',
    },
    {
      id: 'trig-3',
      title: 'Heat sensitivity',
      subtitle: '9 of 12 warm days',
      impactText: 'High impact',
    },
  ],
  summaryParagraph:
    "Over 90 days, Sam's energy averaged 46%, with 11 confirmed PEM events typically delayed two or more days after triggering activity. Primary triggers are social interaction, sustained mental effort and heat sensitivity. Sleep averaged 6h 38m and was frequently broken. These patterns have been consistent across the full tracking period.",
  generatedDateText:
    'Generated by heedly on May 20, 2026 · self-reported + connected wearables · not a diagnostic instrument.',
};

// ─── Component ────────────────────────────────────────────────────────────────

export default function NotesScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();

  const handleBack = () => {
    router.replace('/(tabs)/patterns');
  };

  return (
    <View style={styles.root}>
      {/* Exact Aubade Dawn Atmosphere Background */}
      <DawnBackground />

      <SafeAreaView style={styles.safeArea} edges={['top']}>
        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={[
            styles.scrollContent,
            { paddingTop: 8, paddingBottom: insets.bottom + 180 },
          ]}
          showsVerticalScrollIndicator={false}
          bounces={true}>

          {/* ── Back Chevron ──────────────────────────────────────────────── */}
          <Pressable
            onPress={handleBack}
            style={({ pressed }) => [styles.backButton, pressed && styles.pressed]}
            accessibilityRole="button"
            accessibilityLabel="Go back">
            <Text style={styles.backChevron}>‹</Text>
          </Pressable>

          {/* ── Category Label & Heading ─────────────────────────────────── */}
          <Text style={styles.categoryLabel}>FOR YOUR APPOINTMENT</Text>

          <Text style={styles.mainHeading}>Your notes</Text>

          <Text style={styles.subtitleText}>
            {"Everything you've been living, now on\none page."}
          </Text>

          {/* ── 90-DAY SUMMARY Card ───────────────────────────────────────── */}
          <View style={styles.summary90Card}>
            {/* Header Row */}
            <View style={styles.cardHeaderRow}>
              <Text style={styles.cardHeaderLabel}>90-DAY SUMMARY</Text>
              <Text style={styles.cardHeaderDate}>{NOTES_DATA.dateRange}</Text>
            </View>

            {/* Name & Check-ins Row */}
            <View style={styles.nameRow}>
              <Text style={styles.userNameText}>{NOTES_DATA.userName}</Text>
              <Text style={styles.checkInsText}>{NOTES_DATA.totalCheckInsCount} daily check-ins</Text>
            </View>

            {/* 3 Metric Cards Row */}
            <View style={styles.metricsRow}>
              {NOTES_DATA.metrics.map((metric, idx) => (
                <View key={idx} style={styles.metricBox}>
                  <Text style={styles.metricLabel}>{metric.label}</Text>
                  <Text style={styles.metricValue}>{metric.value}</Text>
                  <Text style={styles.metricSubtext}>{metric.subtext}</Text>
                </View>
              ))}
            </View>
          </View>

          {/* ── TOP TRIGGERS Section ─────────────────────────────────────── */}
          <Text style={styles.groupHeaderLabel}>TOP TRIGGERS</Text>

          <View style={styles.triggersBlock}>
            {NOTES_DATA.triggers.map((trigger) => (
              <View key={trigger.id}>
                <View style={styles.triggerRow}>
                  <View style={styles.triggerLeftBlock}>
                    <Text style={styles.triggerTitle}>{trigger.title}</Text>
                    <Text style={styles.triggerSubtitle}>{trigger.subtitle}</Text>
                  </View>
                  <Text style={styles.impactText}>{trigger.impactText}</Text>
                </View>
                <View style={styles.divider} />
              </View>
            ))}
          </View>

          {/* ── SUMMARY Section ─────────────────────────────────────────── */}
          <Text style={styles.groupHeaderLabel}>SUMMARY</Text>

          <View style={styles.summaryCard}>
            <Text style={styles.summaryParagraphText}>
              {NOTES_DATA.summaryParagraph}
            </Text>
          </View>

          <Text style={styles.disclaimerText}>
            {NOTES_DATA.generatedDateText}
          </Text>

          {/* ── Personal Note Link ───────────────────────────────────────── */}
          <Pressable
            style={({ pressed }) => [styles.personalNoteContainer, pressed && styles.pressed]}
            accessibilityRole="button"
            accessibilityLabel="Add a personal note">
            <Text style={styles.personalNoteText}>Add a personal note ›</Text>
          </Pressable>

        </ScrollView>

        {/* ── Sticky Floating Bottom Action Panel ────────────────────────── */}
        <View style={[styles.bottomPanel, { bottom: insets.bottom > 0 ? insets.bottom + 8 : 16 }]}>
          {/* Main Appointment Button */}
          <Pressable
            style={({ pressed }) => [styles.appointmentButton, pressed && styles.buttonPressed]}
            accessibilityRole="button"
            accessibilityLabel="Prepare for my appointment">
            <SymbolView name="calendar" size={18} tintColor="#FFFFFF" />
            <Text style={styles.appointmentButtonText}>Prepare for my appointment</Text>
          </Pressable>

          {/* Secondary Action Row: Export / Share & Copy Link */}
          <View style={styles.secondaryActionsRow}>
            <Pressable
              style={({ pressed }) => [styles.secondaryBtn, pressed && styles.buttonPressed]}
              accessibilityRole="button"
              accessibilityLabel="Export / Share">
              <SymbolView name="square.and.arrow.up" size={16} tintColor={COLORS.headingDark} />
              <Text style={styles.secondaryBtnText}>Export / Share</Text>
            </Pressable>

            <Pressable
              style={({ pressed }) => [styles.secondaryBtn, pressed && styles.buttonPressed]}
              accessibilityRole="button"
              accessibilityLabel="Copy link">
              <SymbolView name="link" size={16} tintColor={COLORS.headingDark} />
              <Text style={styles.secondaryBtnText}>Copy link</Text>
            </Pressable>
          </View>
        </View>

      </SafeAreaView>
    </View>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },

  glowInner: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: '#EEDCE0',
    opacity: 0.45,
    top: '8%',
    alignSelf: 'center',
  },

  safeArea: {
    flex: 1,
  },

  scrollView: {
    flex: 1,
  },

  scrollContent: {
    paddingHorizontal: Spacing.four,
  },

  pressed: {
    opacity: 0.7,
  },

  buttonPressed: {
    opacity: 0.86,
  },

  // ── Top Header ───────────────────────────────────────────────────────────

  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 4,
  },

  backChevron: {
    fontFamily: 'AvenirNext-Regular',
    fontSize: 28,
    lineHeight: 28,
    color: COLORS.bodyText,
  },

  categoryLabel: {
    fontFamily: 'AvenirNext-DemiBold',
    fontSize: 12,
    color: COLORS.mutedText,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    marginBottom: 6,
  },

  mainHeading: {
    fontFamily: 'AvenirNext-Regular',
    fontSize: 36,
    lineHeight: 44,
    color: COLORS.headingDark,
    marginBottom: 8,
  },

  subtitleText: {
    fontFamily: 'AvenirNext-Regular',
    fontSize: 16.5,
    lineHeight: 23,
    color: '#463332',
    marginBottom: Spacing.four,
  },

  // ── 90-DAY SUMMARY Card ──────────────────────────────────────────────────

  summary90Card: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    paddingVertical: 20,
    paddingHorizontal: 18,
    marginBottom: Spacing.four,
    shadowColor: '#C8A090',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },

  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },

  cardHeaderLabel: {
    fontFamily: 'AvenirNext-DemiBold',
    fontSize: 11,
    letterSpacing: 1.2,
    color: COLORS.mutedText,
  },

  cardHeaderDate: {
    fontFamily: 'AvenirNext-DemiBold',
    fontSize: 12,
    color: COLORS.mutedText,
  },

  nameRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: 16,
  },

  userNameText: {
    fontFamily: 'AvenirNext-Regular',
    fontSize: 24,
    color: COLORS.headingDark,
  },

  checkInsText: {
    fontFamily: 'AvenirNext-Regular',
    fontSize: 12,
    color: COLORS.mutedText,
  },

  metricsRow: {
    flexDirection: 'row',
    gap: 8,
  },

  metricBox: {
    flex: 1,
    backgroundColor: COLORS.metricBg,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 10,
    gap: 2,
  },

  metricLabel: {
    fontFamily: 'AvenirNext-DemiBold',
    fontSize: 10,
    letterSpacing: 0.8,
    color: COLORS.bodyText,
    textTransform: 'uppercase',
  },

  metricValue: {
    fontFamily: 'AvenirNext-DemiBold',
    fontSize: 20,
    color: COLORS.headingDark,
    marginTop: 2,
    marginBottom: 2,
  },

  metricSubtext: {
    fontFamily: 'AvenirNext-Regular',
    fontSize: 11,
    color: COLORS.bodyText,
  },

  // ── Group Headers ────────────────────────────────────────────────────────

  groupHeaderLabel: {
    fontFamily: 'AvenirNext-DemiBold',
    fontSize: 12,
    letterSpacing: 1.8,
    color: COLORS.mutedText,
    textTransform: 'uppercase',
    marginBottom: 10,
    marginTop: Spacing.two,
  },

  // ── Triggers Block ───────────────────────────────────────────────────────

  triggersBlock: {
    marginBottom: Spacing.four,
  },

  triggerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },

  triggerLeftBlock: {
    flex: 1,
    gap: 4,
    marginRight: 12,
  },

  triggerTitle: {
    fontFamily: 'AvenirNext-DemiBold',
    fontSize: 16,
    color: COLORS.headingDark,
  },

  triggerSubtitle: {
    fontFamily: 'AvenirNext-Regular',
    fontSize: 13,
    color: COLORS.mutedText,
  },

  impactText: {
    fontFamily: 'AvenirNext-DemiBold',
    fontSize: 13,
    color: COLORS.accent,
    paddingTop: 2,
  },

  divider: {
    height: 1,
    backgroundColor: COLORS.divider,
  },

  // ── Summary Block ────────────────────────────────────────────────────────

  summaryCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    paddingVertical: 18,
    paddingHorizontal: 18,
    marginBottom: 14,
    shadowColor: '#C8A090',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },

  summaryParagraphText: {
    fontFamily: 'AvenirNext-Regular',
    fontSize: 15,
    lineHeight: 23,
    color: COLORS.headingDark,
  },

  disclaimerText: {
    fontFamily: 'AvenirNext-Regular',
    fontSize: 12.5,
    lineHeight: 18,
    color: COLORS.mutedText,
    marginBottom: 24,
    marginHorizontal: -4,
  },

  // ── Personal Note Link ───────────────────────────────────────────────────

  personalNoteContainer: {
    alignSelf: 'center',
    marginBottom: Spacing.four,
  },

  personalNoteText: {
    fontFamily: 'AvenirNext-DemiBold',
    fontSize: 16,
    color: COLORS.accent,
  },

  // ── Bottom Action Panel ──────────────────────────────────────────────────

  bottomPanel: {
    position: 'absolute',
    left: Spacing.four,
    right: Spacing.four,
    backgroundColor: COLORS.panelBg,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.panelBorder,
    padding: 12,
    gap: 10,
    shadowColor: '#C8A090',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },

  appointmentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.buttonFill,
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: Spacing.three,
    gap: 8,
    shadowColor: '#C05A3A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 5,
  },

  appointmentButtonText: {
    color: COLORS.buttonText,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.1,
  },

  secondaryActionsRow: {
    flexDirection: 'row',
    gap: 10,
  },

  secondaryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.secondaryBtnBg,
    borderWidth: 1,
    borderColor: COLORS.secondaryBtnBorder,
    borderRadius: 18,
    paddingVertical: 13,
    gap: 6,
    shadowColor: '#C8A090',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },

  secondaryBtnText: {
    fontFamily: 'AvenirNext-DemiBold',
    fontSize: 14,
    color: COLORS.headingDark,
  },
});
