// Aubade — Notes / doctor-ready report screens. Exports NotesScreen + NOTES to window.
(function () {
  function NIcon({ name }) {
    const s = { fill: "none", stroke: "currentColor", strokeWidth: 1.7, strokeLinecap: "round", strokeLinejoin: "round" };
    switch (name) {
      case "cal":return <svg viewBox="0 0 24 24" {...s}><rect x="3.5" y="5" width="17" height="16" rx="3.4" /><path d="M3.5 9.5h17M8 3v4M16 3v4" /></svg>;
      case "share":return <svg viewBox="0 0 24 24" {...s}><path d="M12 15.5V4M8.4 7.6 12 4l3.6 3.6" /><path d="M6 12.5V19a1.6 1.6 0 0 0 1.6 1.6h8.8A1.6 1.6 0 0 0 18 19v-6.5" /></svg>;
      case "link":return <svg viewBox="0 0 24 24" {...s}><path d="M9.4 14.6 14.6 9.4" /><path d="M10.6 7.4l1.2-1.2a4 4 0 0 1 5.7 5.7l-1.2 1.2" /><path d="M13.4 16.6l-1.2 1.2a4 4 0 0 1-5.7-5.7l1.2-1.2" /></svg>;
      case "chev":return <svg viewBox="0 0 24 24" {...s}><path d="M9 6l6 6-6 6" /></svg>;
      case "back":return <svg viewBox="0 0 24 24" {...s}><path d="M15 5l-7 7 7 7" /></svg>;
      default:return null;
    }
  }

  function Tile({ label, value, cap }) {
    return (
      <div className="nt-tile">
        <p className="nt-tile-label" style={{ fontSize: "9px" }}>{label}</p>
        <p className="nt-tile-val">{value}</p>
        <p className="nt-tile-cap">{cap}</p>
      </div>);

  }

  function Trigger({ title, detail }) {
    return (
      <div className="nt-trig">
        <div className="nt-trig-main">
          <p className="nt-trig-title">{title}</p>
          <p className="nt-trig-detail">{detail}</p>
        </div>
        <span className="nt-trig-badge">High impact</span>
      </div>);

  }

  function NotesScreen({ data }) {
    return (
      <div className="screen nt-screen">
        <div className="nt-doc" style={{ transform: "translateY(-" + (data.offset || 0) + "px)" }}>
          <div className="sx-nav"><button className="sx-back" aria-label="Back"><NIcon name="back" /></button></div>
          <p className="nt-eyebrow">For your appointment</p>
          <h2 className="nt-title">Your notes</h2>
          <p className="nt-sub">Everything you've been living, now on one page.</p>

          <div className="nt-card">
            <div className="nt-card-head">
              <div>
                <p className="nt-sec">90-day summary</p>
                <p className="nt-name">Sam Wynne</p>
              </div>
              <div className="nt-meta">
                <p className="nt-meta-range">Feb 19 — May 19, 2026</p>
                <p className="nt-meta-count">74 daily check-ins</p>
              </div>
            </div>
            <div className="nt-tiles">
              <Tile label="Avg energy" value="46%" cap="median 48%" />
              <Tile label="Crashes" value="11" cap="≥ 2-day PEM" />
              <Tile label="Sleep" value="6h 38m" cap="often broken" />
            </div>
          </div>

          <p className="nt-sec nt-sec--sp">Top triggers</p>
          <div className="nt-trigs">
            <Trigger title="Social or extended conversation" detail="6 of 6 events" />
            <Trigger title="Mental effort over 4 hours" detail="Strong on screen-heavy days" />
            <Trigger title="Heat sensitivity" detail="9 of 12 warm days" />
          </div>

          <p className="nt-sec nt-sec--sp nt-sec--summary">Summary</p>
          <div className="nt-card nt-card--summary">
            <p className="nt-para">Over 90 days, your energy averaged 46%, with 11 confirmed PEM events typically delayed two or more days after triggering activity. Primary triggers are social interaction, sustained mental effort and heat sensitivity. Sleep averaged 6h 38m and was frequently broken. These patterns have been consistent across the full tracking period.</p>
          </div>

          <p className="nt-prov">Generated by heedly on May 20, 2026 · self-reported + connected wearables · not a diagnostic instrument.</p>

          <button className="nt-addnote">Add a personal note<span className="nt-addnote-chev"><NIcon name="chev" /></span></button>
        </div>

        <div className="nt-topfade"></div>

        <div className="nt-actions">
          <button className="nt-primary"><span className="nt-primary-ic"><NIcon name="cal" /></span>Prepare for my appointment</button>
          <div className="nt-actions-row">
            <button className="nt-ghost"><NIcon name="share" />Export / Share</button>
            <button className="nt-ghost"><NIcon name="link" />Copy link</button>
          </div>
        </div>
      </div>);

  }

  const NOTES = [
  { key: "nt-top", label: "Your notes", offset: 0 },
  { key: "nt-scrolled", label: "Your notes · Scrolled", offset: 520 }];


  Object.assign(window, { NotesScreen, NOTES });
})();